Add Carrion Wiki.gg
KevinPayravi/indie-wiki-buddy pull request #614
Opened 2024-03-21 16:25 UTC by DrWhoFan13

I added Carrion wiki.gg, which I (anonymously) requested yesterday. Considering that the Fandom wiki has _39_ pages, I have no doubt that the fork will go through.

2024-03-21 16:49 UTC, KevinPayravi requested changes
Thanks for the submission! One small fix requested.

2024-03-21 16:49 UTC, KevinPayravi commented on data/sitesEN.json
> +      "origin_base_url": "https://carrion.fandom.com",
Please remove the `https://`

2024-03-21 17:36 UTC, DrWhoFan13 commented
Removed the `https://` as requested.

2024-03-22 08:26 UTC, KevinPayravi approved these changes
Thank you!

2024-03-22 08:26 UTC, merged