Add Wiki: Russian Lethal Company Miraheeze Redirect
KevinPayravi/indie-wiki-buddy pull request #616
Opened 2024-03-22 23:01 UTC by DrWhoFan13

Miraheeze has a complete Russian translation of the Lethal Company Wiki, which also has a Fandom wiki of 72 pages. This Pull Request has a redirect for that wiki.

2024-03-25 04:39 UTC, KevinPayravi requested changes

2024-03-25 04:39 UTC, KevinPayravi commented on data/sitesES.json
> +    "id": "
Stray object here, please remove

2024-03-25 05:28 UTC, DrWhoFan13 commented
Done!

2024-04-05 19:22 UTC, DrWhoFan13 commented
@KevinPayravi

2024-04-06 06:11 UTC, KevinPayravi commented on data/sitesPL.json
> +        "origin_base_url": "halflife.fandom.com/pl",
Looks like this URL should be `half-life`, not `halflife`

2024-04-06 06:16 UTC, KevinPayravi commented
@DrWhoFan13 Apologies for the wait. With these redirects between non-English wikis that utilize the "destination_content_suffix", I've realized there are some issues, depending on the wiki. The redirects only really work when the non-English title is the same as the English one, since on the destination wiki, the language code (e.g. `/es`) is appended to the English title of the article. I've been trying to figure out a good way to gracefully handle when the titles do not match.

2024-04-06 06:38 UTC, DrWhoFan13 commented
So, this isn't gonna be merged unless I remove the code for the Lethal Company Redirect due to the aforementioned issue?

2024-04-06 14:38 UTC, DrWhoFan13 commented
Oh, so it is. I fixed the error.

2024-04-12 21:57 UTC, KevinPayravi commented
> So, this isn't gonna be merged unless I remove the code for the Lethal Company Redirect due to the aforementioned issue?

I'll likely still merge it before the next update, just investigating if there's a better approach to handle these wikis

2024-04-12 22:18 UTC, DrWhoFan13 commented
> I'll likely still merge it before the next update, just investigating if there's a better approach to handle these wikis
Glad to hear it!

2024-04-24 08:31 UTC, KevinPayravi approved these changes

2024-04-24 08:32 UTC, merged