Added Four New Wikis
KevinPayravi/indie-wiki-buddy pull request #639
Opened 2024-04-14 19:35 UTC by DrWhoFan13

Wikis Added:

- Linkinpedia from Linkin Park Fandom Wiki
- NinWiki from Nine Inch Nails Fandom Wiki (They've been around since 1988! How does the fandom only have _24_ articles?!)
- RammWiki from Rammstein Fandom Wiki (RammWiki has more stringent requirements for an account than the average wiki, namely you need to contact them to get an account)
- When They Cry Wiki from When They Cry Fandom

2024-04-16 07:56 UTC, KevinPayravi requested changes
Thank you! Requesting a few small fixes

2024-04-16 07:56 UTC, KevinPayravi commented on data/sitesEN.json
> +    "id": "en-NineInchNails",
IDs should be all lowercase

2024-04-16 07:56 UTC, KevinPayravi commented on data/sitesEN.json
> +    "id": "en-ramm",
Let's make the ID the full name (`en-rammstein`)

2024-04-16 07:56 UTC, KevinPayravi commented on data/sitesEN.json
> +        "origin": " Higurashi no Naku Koro Ni Fandom Wiki",
There's an extra space at the start of the name

2024-04-16 14:37 UTC, DrWhoFan13 commented
Errors have been fixed, just two things to note:

1. NinWiki, for some reason, doesn't have a custom favicon
2. This has the pull requests that [my other PR](https://github.com/KevinPayravi/indie-wiki-buddy/pull/616) has

2024-04-24 08:35 UTC, KevinPayravi approved these changes

2024-04-24 08:35 UTC, merged