Added Several Fextra Redirects
KevinPayravi/indie-wiki-buddy pull request #650
Opened 2024-04-24 18:18 UTC by DrWhoFan13

Added Redirects for:

- Fallout 4 & 76 Fextra wikis to Independent Fallout Wiki
- Minecraft Dungeons Fextra to the Minecraft Wiki
- TOTK Fextra to Zeldapedia
- Darkest Dungeon 2 Fextra to Darkest Dungeon Wiki.gg
- Hollow Knight Silksong Fextra to Hollow Knight Wiki
- Destiny Fextras to Destinypedia

2024-04-24 18:31 UTC, KevinPayravi requested changes
Thanks for the PR! Please make sure the wikis in each `origins` array are separated by commas. I recommend editing JSONs in an editor that does JSON validation to catch these sort of syntax errors.

2024-04-24 18:43 UTC, DrWhoFan13 commented
Done!

2024-04-24 19:14 UTC, KevinPayravi requested changes

2024-04-24 19:14 UTC, KevinPayravi commented on data/sitesEN.json
> +      },
Need to remove trailing commas after the last object in each array

2024-04-24 21:21 UTC, DrWhoFan13 commented
Okay, _now_ it should be done.

2024-04-25 02:59 UTC, KevinPayravi approved these changes
Thank you!

2024-04-25 02:59 UTC, merged