Adding SCP: Secret Laboratory Wiki
KevinPayravi/indie-wiki-buddy pull request #656
Opened 2024-04-28 17:57 UTC by DrWhoFan13

Contains a redirect to the SCP: Secret Laboratory Wiki, which I've previously submitted a request to include via the Google Forum.

2024-05-02 00:55 UTC, KevinPayravi requested changes

2024-05-02 00:55 UTC, KevinPayravi commented on data/sitesEN.json
> +    "destination_content_path": "/"
Content path should be `/index.php?title=`

2024-05-02 00:55 UTC, KevinPayravi commented on data/sitesEN.json
>    },
Please add a `tags` array with `"official"` as a value.

```
"tags": [
  "official"
]
```

2024-05-02 00:55 UTC, KevinPayravi commented on data/sitesEN.json
> +    "destination": "SCP: Secret Laboratory Offical Wiki",
Please remove "Official" from the title - it might be formally part of the title, but brevity is better since we don't have a lot of space in the UI

2024-05-02 01:06 UTC, KevinPayravi requested changes

2024-05-02 01:06 UTC, KevinPayravi commented on data/sitesEN.json
> +    "destination_content_path": "/index.php?title="
Missing trailing comma; please put the JSON through a validator to catch errors like these

2024-05-02 01:33 UTC, DrWhoFan13 commented
Everything has been corrected, now it should work.

2024-05-03 00:12 UTC, KevinPayravi approved these changes
Thank you!

2024-05-03 00:12 UTC, merged